---
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "90%"
)
```

# USK

<!-- badges: start -->
<!-- badges: end -->

*usktest* is a function used to do the Scott-Knott
 cluster analysis (1974) for unbalanced designs proposed at 2017 (CONRADO, T. V; FERREIRA, D. F.; SCAPIM, C. A.; MALUF, W. R.).
 To learn more, see the article: <http://ref.scielo.org/ws792m>.

## Installation

You can install the the development version from [github](https://github.com/felipe179971/USK) with:

``` r
# install.packages("devtools")
devtools::install_github("felipe179971/USK",force = TRUE)
```
## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(USK)
## basic example code
set.seed(3)
taus=c(4,4,-4,-4,9,-9)
treatment<-as.factor(rep(c(paste("trat",seq(1:length(taus)))),3))
error<-rnorm(3*length(taus),0,1)
y<-2+taus+error
y[round(runif(1,min=1,max=length(y)),0)]<-NA
dataset<-data.frame(y,treatment)

plot_usk(usktest(y~treatment,dataset,ANOVA = T))
```

